### ISSUE TITLE
Build size on Next.js 11

### ISSUE THREAD

**Issue by takeshi-evan** [aliogaili/meronex-icons#6]
**Describe the bug**

using Import as:
import { IoLogoFacebook, IoLogoInstagram  } from '@meronex/icons/ios'
Build contains the whole IOS pack

**Expected behavior**
Build containing only the icons imported

**Screenshots**
![Screen Shot 2021-09-08 at 11 14 03](https://user-images.githubusercontent.com/23573195/132526023-a12167e7-7681-4b32-afe7-8831f614b502.png)

**Framework and versions**
Next.Js: 11.1.2
Meronex Icons: 4.0.0
Webpack 5 (Default of Next.Js)

**Additional context**
Am I missing something on the usage of the library?

**Comment by aogaili** [comment]
Can you try to import directly each individual icon? Instead of using destructing and let me know.

e.g `import FaBeer from '@meronex/icons/fa/FaBeer';`
